version: '3.4'

services:
  reverse-proxy:
    restart: always
    image: traefik:v2.2
    container_name: traefik
    ports:
      - 443:443
      - 8080:8080
      - 8082:8082
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./dynamic_conf.toml:/etc/traefik/dynamic_conf.toml
    labels:
      - "traefik.enable=true"
    networks:
      - proxy

  auth-server:
    restart: always
    container_name: auth-server
    ports:
      - 8081:8081
    image: auth-server
    build:
      dockerfile: Dockerfile
      context: ../../.
    command: -repo=traefik 
    labels:
      - "traefik.enable=true"
    networks:
      - proxy

networks:
  proxy:
    external: true
