---
http:
  services:
    auth-server:
      loadBalancer:
        servers:
          - url: http://auth-server:8081/

  middlewares:
    test-auth:
      forwardAuth:
        address: http://auth-server:8081/auth
        authResponseHeaders:
          - "X-Auth-User"
          - "X-Secret"
        trustForwardHeader: true

  routers:
    token-router:
      rule: "Path(`/token`)"
      service: auth-server
      entrypoints:
        - http
      priority: 2

    auth-router:
      rule: "HostRegexp(`{host:.*}`)"
      middlewares:
        - test-auth
      service: auth-server
      entrypoints:
        - http
      priority: 1
